site: # required
  host: https://www.narukoshin.me/login # required
  method: POST # required

bruteforce: # required
  field: password # required

  # method #1
  from: list
  list:
   - example password
   - example password 2

  # method #2
  from: file
  file: /usr/share/wordlists/rockyou.txt
  
  # method 3
  from: stdin
  
  # This option turns off "trying password" messages
  no_verbose: false # optional
  
  # this option will save the password in the file
  output: /home/naru/my_target/password.txt
  
  threads: 20 # optional | default: 5

headers: # optional
  - name: User-Agent
    value: "Mozilla/5.0 (Macintosh; Intel Mac OS)"
  - name: Content-Type
    value: "application/x-www-form-urlencoded; charset=UTF-8"

fields: # optional
  - name: username
    value: admin

on_fail: # required - will be ignored if on_pass is added
  message: Invalid username
  
on_pass: # optional
  message: Welcome
  
crawl: # optional
  name: field-name
  search: ([a-z0-9]+){32} # a regex to find the token
