site:
  host: https://www.narukoshin.me/login
  method: POST

bruteforce:
  field: password
  type: list
  list:
   - example password

headers:
  - name: User-Agent
    value: "Mozilla/5.0 (Macintosh; Intel Mac OS)"
  - name: Content-Type
    value: "application/x-www-form-urlencoded; charset=UTF-8"

fields:
  - name: username
    value: admin

on_fail:
  message: Invalid username