site: # required
  host: https://www.narukoshin.me/login # required
  method: POST # required

bruteforce: # required
  field: password # required

  # method #1
  from: list
  list:
   - example password
   - example password 2

  # method #2
  from: file
  file: ./test

  threads: 20 # optional | default: 5

headers: # optional
  - name: User-Agent
    value: "Mozilla/5.0 (Macintosh; Intel Mac OS)"
  - name: Content-Type
    value: "application/x-www-form-urlencoded; charset=UTF-8"

fields: # optional
  - name: username
    value: admin

on_fail: # required
  message: Invalid username